### ISSUE TITLE
Failing for bitbucket

### ISSUE THREAD

**Issue by vvasuki** [wercker/step-add-to-known_hosts#20]
Code:

```
    - add-to-known_hosts:
        hostname: bitbucket.org
        fingerprint: 97:8c:1b:f2:6f:14:6b:5c:3b:ec:aa:46:46:74:7c:40
        type: rsa
```

Result:

```
--> Running step: add-to-known_hosts
/etc/ssh/ssh_known_hosts does not exists, touching it and chmod it to 644
# bitbucket.org:22 SSH-2.0-conker_1.1.53-1da6f80 app-129
Searching for keys that match fingerprint 97:8c:1b:f2:6f:14:6b:5c:3b:ec:aa:46:46:74:7c:40
Skipped adding a key to known_hosts, it did not match the fingerprint (SHA256:zzXQOXSRBEiUtuE8AikJYKwbHaxvSc0ojez9YXaGp1A)
```

**Comment by vvasuki** [comment]
The below seems to work fine, though:
```
    - add-to-known_hosts:
        hostname: bitbucket.org
        fingerprint: zzXQOXSRBEiUtuE8AikJYKwbHaxvSc0ojez9YXaGp1A
        type: rsa
```
